/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netbanking;

import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author makka
 */
public class transferfunds extends javax.swing.JFrame {

    public transferfunds() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    int acnum=0;
    public transferfunds(int racno)
    {
        initComponents();
        acnum = racno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btntransfer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        accnoTF = new javax.swing.JTextField();
        recAccNo = new javax.swing.JTextField();
        amtTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Transfer money");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Your account no. :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Reciever Account no. :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Amount:");

        btntransfer.setBackground(new java.awt.Color(102, 102, 102));
        btntransfer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btntransfer.setText("Transfer Funds");
        btntransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransferActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("<-");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        accnoTF.setBackground(new java.awt.Color(204, 204, 204));
        accnoTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        accnoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accnoTFActionPerformed(evt);
            }
        });

        recAccNo.setBackground(new java.awt.Color(204, 204, 204));
        recAccNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        amtTF.setBackground(new java.awt.Color(204, 204, 204));
        amtTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amtTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amtTFActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("What's this for:");

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netbanking/banklogo11.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)
                        .addGap(216, 216, 216)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(recAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(accnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(amtTF, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(btntransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel1)))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(accnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(recAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(amtTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btntransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransferActionPerformed
        // TODO add your handling code here:
        
     try
     {
         PreparedStatement ps;
                 ResultSet rs,rscheck,rschecksendbal;
         Class.forName("com.mysql.jdbc.Driver");
         
         Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/netbanking","root","meenu1");
         Statement st1=(Statement) con.createStatement();
         if(!(accnoTF.getText().isEmpty() || recAccNo.getText().isEmpty() || amtTF.getText().isEmpty()))
         {
         int accno = Integer.parseInt(accnoTF.getText());
         int accnoRecv = Integer.parseInt(recAccNo.getText());
         int amt = Integer.parseInt(amtTF.getText());
         
         if(acnum==accno)
         {
         String check="Select Account_no from registered_customers where Account_no = "+accno+";";
         String checkRecv="Select * from bank_customers where Account_no = "+accnoRecv+";";
         String checksend="Select * from bank_customers where Account_no = "+accno+";";
         
         
         rs=st1.executeQuery(check);
         if(rs.next())
         {
             rscheck=st1.executeQuery(checkRecv);
             if(rscheck.next())
             {
                 int bal = rscheck.getInt("account_balance");
              
                 rschecksendbal = st1.executeQuery(checksend);
                 if(rschecksendbal.next())
                 {
                 int balsender = rschecksendbal.getInt("account_balance");
                 
                 if(balsender>=amt)
                 {
                 int finalbal = bal+amt;
                 int finalbal1=balsender-amt;
             
                 String q = "Update bank_customers set account_balance ="+finalbal+" where Account_no="+accnoRecv+";";
                 String q1 = "Update bank_customers set account_balance ="+finalbal1+" where Account_no="+accno+";";
                 st1.executeUpdate(q);
                 st1.executeUpdate(q1);
                 
                 DateFormat df=new SimpleDateFormat();
                 Date curr=(Date) Calendar.getInstance().getTime();
                 String today = df.format(curr);
                 
                 String tq= "INSERT INTO `transactions` VALUES(' "+accno+"','"+today+"','"+amt+"','"+accnoRecv+"','"+finalbal+"');";
                 String tqs= "INSERT INTO `tr` VALUES(' "+accno+"','"+today+"','"+amt+"','"+accnoRecv+"','"+finalbal1+"','"+0+"');";
                 String tq1= "INSERT INTO `transactions` VALUES(' "+accnoRecv+"','"+today+"','"+amt+"','"+accnoRecv+"','"+finalbal+"');";
                 String tq2= "INSERT INTO `tr` VALUES(' "+accnoRecv+"','"+today+"','"+0+"','"+accno+"','"+finalbal+"','"+amt+"');";
                // JOptionPane.showMessageDialog(null,"Funds Sent Successfully");
                 st1.executeUpdate(tq2);
                 st1.executeUpdate(tqs);
                 
                 JOptionPane.showMessageDialog(null,"Funds Sent Successfully");
                  ebankingoptions ebo = new ebankingoptions(acnum);
                ebo.setVisible(true);
                ebo.setLocationRelativeTo(null);
                this.hide();
                 }
             else{
                 JOptionPane.showMessageDialog(null,"Insufficient funds");
                 loginmain lg = new loginmain();
                 lg.setVisible(true);
                 this.hide();
                 lg.setLocationRelativeTo(null);
             }     
             }
             else
             {
                 JOptionPane.showMessageDialog(null,"Funds sent successfully");
             }
             }
            
         }         
         else
         {
             JOptionPane.showMessageDialog(null,"invalid account");
         }
         }
         else{
             JOptionPane.showMessageDialog(null,"Account number mis-match");
         }
         }
             else
             {
                 JOptionPane.showMessageDialog(null,"Empty fields not allowed");
             }
         
        /* rscheck=st1.executeQuery(check);
         if(rscheck.next())
         {
             int accre=rscheck.getInt("Account_no");
             if(accno == accre )
             {
                 
                 JOptionPane.showMessageDialog(null,"Mil gaya");
             }
         }*/
     }
     catch(SQLException e)
     {
                 
     }  catch (ClassNotFoundException ex) {
            Logger.getLogger(transferfunds.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btntransferActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
 ebankingoptions ebo = new ebankingoptions(acnum);
                ebo.setVisible(true);   
                this.hide(); 
                ebo.setLocationRelativeTo(null);
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void accnoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accnoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accnoTFActionPerformed

    private void amtTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amtTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amtTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transferfunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transferfunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transferfunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transferfunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transferfunds().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accnoTF;
    private javax.swing.JTextField amtTF;
    private javax.swing.JButton btntransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField recAccNo;
    // End of variables declaration//GEN-END:variables
}
